name: Python Formatting & Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Auto-Fix Code Style
        run: |
          black .
          isort .

      - name: Lint Check
        run: |
          flake8 --ignore=E501  # Ignores long-line warnings

      - name: Commit and Push Fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-format code with Black and isort" || echo "No changes to commit"
          git push
        continue-on-error: true