name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint Check 
        run: |
          pip install flake8
          flake8 --ignore=E501 . 

      - name: Run Tests
        run: |
          if [ -f pytest.ini ]; then
            pip install pytest
            pytest
          else
            echo "No tests found, skipping..."
          fi










